############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: https://zhuhongjing19.github.io/hongjingzhu.github.io/
  - path: https://zhuhongjing19.github.io/hongjingzhu.github.io/

# Install any Hugo Blox within the `hugo-blox/blox/` folder
mounts:
  - source: https://zhuhongjing19.github.io/hongjingzhu.github.io/
    target: https://zhuhongjing19.github.io/hongjingzhu.github.io/
    includeFiles: '**.html'
  - source: https://zhuhongjing19.github.io/hongjingzhu.github.io/
    target: https://zhuhongjing19.github.io/hongjingzhu.github.io/
    includeFiles: '**.html'
  - source: https://zhuhongjing19.github.io/hongjingzhu.github.io/
    target: https://zhuhongjing19.github.io/hongjingzhu.github.io/
    includeFiles: '**.css'
  - source: layouts
    target: layouts
  - source: assets
    target: assets
